apiVersion: keycloak.platformref.upbound.io/v1alpha1
kind: User
metadata:
  name: argocd-admin-user
  namespace: default
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: platform-ref-aws-cnoe
    username: argocd-admin
    firstname: argocd
    lastname: admin
    email: argocd-admin@upboundrocks.cloud
    group: argocd-admin
    initialPassword:
      - valueSecretRef:
          key: password
          name: argocd-admin-user
          namespace: default
        temporary: true
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-admin-user
  namespace: default
type: Opaque
stringData:
  password: my-secret-password
